const testData = {
  docs: [
    {
      _id: '5cd99d4bde30eff6ebccfd06',
      height: 'Tall',
      race: 'Elf',
      gender: 'Female',
      birth: 'YT 1362',
      spouse: 'Celeborn',
      death: 'Still alive: Departed over the sea on ,September 29 ,3021',
      realm: 'Eregion,Lothlórien,Caras Galadhon',
      hair: 'Golden',
      name: 'Galadriel',
      wikiUrl: 'http://lotr.wikia.com//wiki/Galadriel',
    },
    {
      _id: '5cd99d4bde30eff6ebccfea0',
      height: '',
      race: 'Maiar',
      gender: 'Male',
      birth: 'Before the the Shaping of Arda',
      spouse: '',
      death: 'January 253019 ,Battle of the Peak immortal',
      realm: '',
      hair: 'Grey, later white',
      name: 'Gandalf',
      wikiUrl: 'http://lotr.wikia.com//wiki/Gandalf',
    },
    {
      _id: '5cd99d4bde30eff6ebccfd23',
      height: '',
      race: 'Dwarf',
      gender: 'Male',
      birth: 'TA 2879',
      spouse: '',
      death: 'Unknown (Departed to ,Aman ,FO 120,)',
      realm: '',
      hair: 'Auburn',
      name: 'Gimli',
      wikiUrl: 'http://lotr.wikia.com//wiki/Gimli',
    },
    {
      _id: '5cd99d4bde30eff6ebccfe9e',
      height: '',
      race: 'Hobbit',
      gender: 'Male',
      birth: 'TA 2430',
      spouse: '',
      death: 'March 25 ,3019',
      realm: '',
      hair: '',
      name: 'Gollum',
      wikiUrl: 'http://lotr.wikia.com//wiki/Gollum',
    },
    {
      _id: '5cd99d4bde30eff6ebccfd81',
      height: '',
      race: 'Elf',
      gender: 'Male',
      birth: '',
      spouse: '',
      death: 'Still alive, departed to ,Aman ,FO 120',
      realm: '',
      hair: 'Uncertain (book), Blonde (films)',
      name: 'Legolas',
      wikiUrl: 'http://lotr.wikia.com//wiki/Legolas',
    },
    {
      _id: '5cd99d4bde30eff6ebccfea4',
      height: '',
      race: 'Maiar',
      gender: 'Male',
      birth: 'Before the creation of ,Arda',
      spouse: 'None',
      death: '3 November ,3019',
      realm: 'Isengard,Nan Curunír',
      hair: 'White',
      name: 'Saruman',
      wikiUrl: 'http://lotr.wikia.com//wiki/Saruman',
    },
  ],
  total: 6,
  limit: 1000,
  offset: 0,
  page: 1,
  pages: 1,
};

export default testData;
